// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgI2yFheFu1Q1uq0DiC94xVMYQzCGvHJw',
    appId: '1:866010536203:web:4aec262af1a1e551b02a0e',
    messagingSenderId: '866010536203',
    projectId: 'first-c458b',
    authDomain: 'first-c458b.firebaseapp.com',
    storageBucket: 'first-c458b.appspot.com',
    measurementId: 'G-PXZBY57152',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsKa75snKOTf1OcJfV1S0Awi9n-EN-kjY',
    appId: '1:866010536203:android:a478ac07049d56e4b02a0e',
    messagingSenderId: '866010536203',
    projectId: 'first-c458b',
    storageBucket: 'first-c458b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCniA3BSrZfIxfowvAr4u-j0k5mBL7IjA',
    appId: '1:866010536203:ios:f95e22de4a9cb971b02a0e',
    messagingSenderId: '866010536203',
    projectId: 'first-c458b',
    storageBucket: 'first-c458b.appspot.com',
    iosClientId: '866010536203-gif0knachj5m6vsfrcus5kcstpor8bl4.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCniA3BSrZfIxfowvAr4u-j0k5mBL7IjA',
    appId: '1:866010536203:ios:f95e22de4a9cb971b02a0e',
    messagingSenderId: '866010536203',
    projectId: 'first-c458b',
    storageBucket: 'first-c458b.appspot.com',
    iosClientId: '866010536203-gif0knachj5m6vsfrcus5kcstpor8bl4.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseauth',
  );
}
